language: go

go:
  - 1.3
  - 1.4
  - 1.5
  - tip

script: 
 - go test -cpu=2 ./...
 - go test -cpu=2 -tags=noasm ./...
 - go test -cpu=2 -short -race ./...
 - go test -cpu=2 -short -race -tags=noasm ./...
