language: go

os:
  - linux
  - osx

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - master

env:
  - GO111MODULE=off

install:
 - go get ./...
 - go get github.com/klauspost/compress-fuzz

script:
 - diff <(gofmt -d .) <(printf "")
 - go test -cpu=2 ./...
 - go test -cpu=2 -tags=noasm ./...
 - go test -cpu=1,4 -short -race ./...
 - go build github.com/klauspost/compress/s2/cmd/s2c && go build github.com/klauspost/compress/s2/cmd/s2d && s2c s2c && s2d s2c.s2 && rm s2c && rm s2d && rm s2c.s2

jobs:
  allow_failures:
    - go: 'master'
  fast_finish: true
  include:
    - stage: 386 linux test
      go: 1.15.x
      script:
        - GOOS=linux GOARCH=386 go test -short ./...

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | VERSION=v0.127.0 bash || true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
    go: 1.15.x

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
