language: go

os:
  - linux
  - osx

arch:
  - amd64

go:
  - 1.14.x
  - 1.15.x
  - 1.16.x
  - master

env:
  - GO111MODULE=off CGO_ENABLED=0

install:
 - go get ./...

script:
 - go test -cpu=2 ./...
 - go test -cpu=2 -tags=noasm ./...
 - CGO_ENABLED=1 go test -cpu=1,4 -short -race ./...
 - go build github.com/klauspost/compress/s2/cmd/s2c && go build github.com/klauspost/compress/s2/cmd/s2d && s2c s2c && s2d s2c.s2 && rm s2c && rm s2d && rm s2c.s2

jobs:
  allow_failures:
    - go: 'master'
  fast_finish: true
  include:
    - stage: misc one-off tests
      go: 1.16.x
      script:
        - diff <(gofmt -d .) <(printf "")
        - GOOS=linux GOARCH=386 go test -short ./... # test on 386/32 bits.
        - curl -sfL https://git.io/goreleaser | VERSION=v0.157.0 sh -s -- check # check goreleaser config for deprecations
        - curl -sL https://git.io/goreleaser | VERSION=v0.157.0 sh -s -- --snapshot --skip-publish --rm-dist
    - stage: arm64 tests
      arch: arm64
      go:
        - 1.16.x
      script:
        - go test -cpu=2 ./s2
        - go test -cpu=2 -tags=noasm ./s2
        - go build github.com/klauspost/compress/s2/cmd/s2c && go build github.com/klauspost/compress/s2/cmd/s2d && s2c s2c && s2d s2c.s2 && rm s2c && rm s2d && rm s2c.s2

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | VERSION=v0.157.0 bash || true
  on:
    tags: true
    condition: ($TRAVIS_OS_NAME = linux) && ($TRAVIS_CPU_ARCH = amd64)
    go: 1.16.x
branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
